name: inscription_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  image_picker: ^1.0.4
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.0
  pdf: ^3.11.1
  printing: ^5.13.4
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - assets/branding/app_icon.png
    - assets/branding/logo_wordmark.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/branding/app_icon.png"
  min_sdk_android: 21


